// This code generated by http://json2csharp.com/

using System;
using System.Collections.Generic;

public class ExtraStatsInfo
{
    public string name { get; set; }
    public int precision { get; set; }
}

public class Record
{
    public int losses { get; set; }
    public int ties { get; set; }
    public int wins { get; set; }
}

public class Ranking
{
    public int dq { get; set; }
    public List<int> extra_stats { get; set; }
    public int matches_played { get; set; }
    public object qual_average { get; set; }
    public int rank { get; set; }
    public Record record { get; set; }
    public List<double> sort_orders { get; set; }
    public string team_key { get; set; }
}

public class SortOrderInfo
{
    public string name { get; set; }
    public int precision { get; set; }
}

public class RankingsData
{
    public List<ExtraStatsInfo> extra_stats_info { get; set; }
    public List<Ranking> rankings { get; set; }
    public List<SortOrderInfo> sort_order_info { get; set; }
}
